# Site
name: 'Cloudinesia'
description: 'Making an effort to Blog about Cloud and Tech.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
disqus: 'cloudinesia'
email: 'cloudinesia@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    asadshamlan:
      name:           Asad Shamlan
      site:           https://cloudinesia.com
      avatar:         assets/images/avatar1.jpg
      bio:            "Making an effort to write about tech."
      email:          asad.shamlan@gmail.com
      twitter:        https://twitter.com/asadshamlan

    # jane:
    #   name:           Jane
    #   site:           https://www.wowthemes.net
    #   avatar:         /assets/images/avatar2.jpg
    #   bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    #   email:          fakemail@gmail.com
    #   twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: asadshamlan
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]